SELECT * FROM Flight

ALTER TABLE Flight
ADD Airline_ID INT NULL;

UPDATE Flight
SET Airline_ID = 1;

ALTER TABLE Flight
ALTER COLUMN Airline_ID INT NOT NULL;

ALTER TABLE Flight
ADD CONSTRAINT FK_Flight_Airline
FOREIGN KEY (Airline_ID)
REFERENCES Airline(Airline_ID)
ON DELETE NO ACTION
ON UPDATE CASCADE;

SELECT * FROM Airline;

ALTER TABLE Flight
ALTER COLUMN Airline_ID INT NOT NULL;

ALTER TABLE Flight
ADD CONSTRAINT FK_Flight_Airline
FOREIGN KEY (Airline_ID)
REFERENCES Airline(Airline_ID)
ON DELETE NO ACTION
ON UPDATE CASCADE;
---
ALTER TABLE Flight
ADD CONSTRAINT FK_Flight_Gate
FOREIGN KEY (Gate_ID)
REFERENCES Gate(Gate_ID)
ON DELETE SET NULL
ON UPDATE CASCADE;

